package com.example.heartrate.fhirstore;

import ca.uhn.fhir.context.FhirContext;
import java.util.List;
import java.util.Optional;
import org.hl7.fhir.r4.model.Patient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Component;

/**
 * The administrative half of the record: Patients, kept as FHIR in this service's own database.
 *
 * <p>One table, one row per resource, the resource stored as the JSON it is. A column per field
 * would have to change every time a profile said a Patient may carry something new; what is pulled
 * out into columns is only what has to be found. Nothing here knows that the other half of a
 * patient's record is an openEHR composition — the correspondence travels as an ordinary identifier
 * on the resource, and openEHR keeps its own anchor in {@code EHR_STATUS}.
 *
 * <p>The database is reached on demand and never at startup, and the table is created on the first
 * use that finds it missing. That is what keeps the two halves independent inside one service: with
 * this database down the service still starts, EHRbase still answers, and the patients fall back to
 * how the configuration seeds them.
 */
@Component
public class FhirStore {

    private static final Logger log = LoggerFactory.getLogger(FhirStore.class);

    /** The same table the separate FHIR server used to keep, so its rows carry straight over. */
    private static final String SCHEMA = """
            CREATE TABLE IF NOT EXISTS stored_resource (
                pk            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                resource_type VARCHAR(64)  NOT NULL,
                resource_id   VARCHAR(128) NOT NULL,
                json          TEXT         NOT NULL,
                updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                UNIQUE (resource_type, resource_id)
            )""";

    private final JdbcClient jdbc;
    private final FhirContext fhirContext;
    private volatile boolean schemaReady;

    public FhirStore(JdbcClient jdbc, FhirContext fhirContext) {
        this.jdbc = jdbc;
        this.fhirContext = fhirContext;
    }

    /**
     * Writes a patient under the id it carries, creating it when it is not there.
     *
     * <p>An upsert rather than an insert so that seeding the demo patients is idempotent: restarting
     * this service must not leave a second Max Mustermann behind.
     *
     * @return true when the patient was new
     */
    public boolean upsert(Patient patient) {
        ensureSchema();
        var id = patient.getIdElement().getIdPart();
        boolean existed = jdbc.sql("SELECT count(*) FROM stored_resource "
                        + "WHERE resource_type = 'Patient' AND resource_id = :id")
                .param("id", id)
                .query(Long.class)
                .single() > 0;
        jdbc.sql("""
                        INSERT INTO stored_resource (resource_type, resource_id, json, updated_at)
                        VALUES ('Patient', :id, :json, now())
                        ON CONFLICT (resource_type, resource_id)
                        DO UPDATE SET json = EXCLUDED.json, updated_at = EXCLUDED.updated_at""")
                .param("id", id)
                .param("json", fhirContext.newJsonParser().encodeResourceToString(patient))
                .update();
        return !existed;
    }

    /**
     * One patient, or nothing — also when the database cannot be reached, which callers treat the
     * same way: fall back to the roster rather than fail a request about readings.
     */
    public Optional<Patient> read(String id) {
        try {
            ensureSchema();
            return jdbc.sql("SELECT json FROM stored_resource "
                            + "WHERE resource_type = 'Patient' AND resource_id = :id")
                    .param("id", id)
                    .query(String.class)
                    .optional()
                    .map(this::decode);
        } catch (Exception e) {
            log.debug("Patient {} could not be read from the FHIR store: {}", id, e.getMessage());
            return Optional.empty();
        }
    }

    /** Every patient the store holds, by id. Throws when the database cannot be reached. */
    public List<Patient> all() {
        ensureSchema();
        return jdbc.sql("SELECT json FROM stored_resource "
                        + "WHERE resource_type = 'Patient' ORDER BY resource_id")
                .query(String.class)
                .list()
                .stream()
                .map(this::decode)
                .toList();
    }

    /**
     * Creates the table the first time it is needed and the database is there to take it.
     *
     * <p>Not at startup: a service that insisted on this database before it would start could not
     * draw the chart while the database was down, and the two halves would no longer fail apart.
     */
    private void ensureSchema() {
        if (schemaReady) {
            return;
        }
        jdbc.sql(SCHEMA).update();
        schemaReady = true;
    }

    private Patient decode(String json) {
        return fhirContext.newJsonParser().parseResource(Patient.class, json);
    }
}
