import type {
  AqlExample,
  AqlResult,
  DayHistory,
  HeartRateSeries,
  OperationOutcome,
  MappingRule,
  MappingSource,
  SaveResult,
  TemplateView,
  Trace,
  TrafficEntry,
  TraceSample,
} from './types';
import { language } from './i18n.svelte';

/** Calls to the Gradle backend. Vite proxies these to :18080 in development. */

/**
 * Every request says which language it wants. The backend generates most of the teaching text —
 * the pipeline stages, what each mapping did — and resolves `Accept-Language` per request, so this
 * is what keeps its prose and the frontend's in the same language.
 */
function headers(extra: Record<string, string> = {}): Record<string, string> {
  return { 'Accept-Language': language(), ...extra };
}

/**
 * A 404 on an endpoint the frontend knows about almost always means one thing: the backend running
 * on :18080 was started before this endpoint existed. Saying so beats making someone wonder whether
 * their data is missing.
 */
function failure(response: Response, what: string): Error {
  if (response.status === 404) {
    return new Error(
      `${what} is not available (HTTP 404) — the backend is running an older build. ` +
        'Restart it with `cd backend && ./gradlew bootRun`.',
    );
  }
  return new Error(`${what} failed (HTTP ${response.status})`);
}

export async function fetchSeries(days = 30): Promise<HeartRateSeries> {
  // no-store because this is reloaded straight after a write: a cached copy would show the value
  // that was just corrected and look exactly like a correction that did not take.
  const response = await fetch(`/api/heart-rate?days=${days}`, {
    cache: 'no-store',
    headers: headers(),
  });
  if (!response.ok) throw new Error(`Could not load heart rate data (HTTP ${response.status})`);
  return response.json() as Promise<HeartRateSeries>;
}

/**
 * True when the backend is older than this page — it does not know an endpoint the page needs.
 *
 * <p>The backend runs on the host while the frontend runs in a container, so restarting one and not
 * the other is easy, and the symptoms are misleading: corrections that never appear, empty tabs.
 */
export async function backendIsCurrent(): Promise<boolean> {
  try {
    const response = await fetch('/api/about', { cache: 'no-store', headers: headers() });
    if (!response.ok) return false;
    const about = (await response.json()) as { capabilities?: string[] };
    return (about.capabilities ?? []).includes('composition-versioning');
  } catch {
    // Unreachable is a different problem, with its own message on the chart.
    return true;
  }
}

/**
 * Sends a FHIR Bundle to the import endpoint. Answers with an OperationOutcome saying what went
 * in and what did not.
 */
export async function importFile(json: string): Promise<OperationOutcome> {
  const response = await fetch('/fhir/Bundle', {
    method: 'POST',
    headers: headers({ 'Content-Type': 'application/json' }),
    body: json,
  });
  const body = (await response.json().catch(() => null)) as OperationOutcome | null;
  if (!body || body.resourceType !== 'OperationOutcome') {
    throw new Error(`The import failed (HTTP ${response.status})`);
  }
  return body;
}

/**
 * A month of made-up readings as a FHIR Bundle, ending today. Generated by the backend on every
 * call rather than checked in, so it cannot fall out of the chart's 30-day window.
 */
export async function fetchSampleBundle(days = 30): Promise<string> {
  const response = await fetch(`/fhir/Bundle/$sample?days=${days}`, {
    cache: 'no-store',
    headers: headers(),
  });
  if (!response.ok) throw failure(response, 'The sample data');
  return response.text();
}

/** Fetches everything stored as a FHIR Bundle, for download. */
export async function exportBundle(days = 30): Promise<string> {
  const response = await fetch(`/fhir/Observation?days=${days}`, { headers: headers() });
  if (!response.ok) throw new Error(`Could not export (HTTP ${response.status})`);
  return response.text();
}

/**
 * Runs one reading through the whole pipeline and keeps every intermediate form. A dry run
 * unless `store` is set, in which case the composition really is written to EHRbase.
 */
export async function runTrace(json: string, store = false): Promise<Trace> {
  const response = await fetch(`/api/trace?store=${store}`, {
    method: 'POST',
    headers: headers({ 'Content-Type': 'application/json' }),
    body: json,
  });
  if (!response.ok) throw failure(response, 'The trace');
  return response.json() as Promise<Trace>;
}

/** The ready-made inputs the inspector offers. */
export async function fetchTraceSamples(): Promise<TraceSample[]> {
  const response = await fetch('/api/trace/samples', { headers: headers() });
  if (!response.ok) throw failure(response, 'The trace inspector');
  return response.json() as Promise<TraceSample[]>;
}

/** Calls to openFHIR and EHRbase the backend has made since `since`, oldest first. */
export async function fetchTraffic(since = 0): Promise<TrafficEntry[]> {
  const response = await fetch(`/api/traffic?since=${since}`, { headers: headers() });
  if (!response.ok) throw failure(response, 'The traffic console');
  return response.json() as Promise<TrafficEntry[]>;
}

export async function clearTraffic(): Promise<void> {
  const response = await fetch('/api/traffic/clear', { method: 'POST', headers: headers() });
  if (!response.ok) throw failure(response, 'Clearing the traffic');
}

/**
 * Posts one Observation to the FHIR endpoint. Manual entry builds the resource in the browser and
 * sends it here, so typed-in readings take exactly the path an external system's would.
 */
export async function postObservation(observation: unknown): Promise<void> {
  const response = await fetch('/fhir/Observation', {
    method: 'POST',
    headers: headers({ 'Content-Type': 'application/fhir+json' }),
    body: JSON.stringify(observation),
  });
  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(
      `The Observation was not accepted (HTTP ${response.status})${detail ? `: ${detail.slice(0, 200)}` : ''}`,
    );
  }
}

/**
 * Every version of what is recorded for one day, including the values it no longer holds.
 * openEHR's revision history, not FHIR's — the two are not the same thing.
 */
export async function fetchDayHistory(date: string): Promise<DayHistory> {
  const response = await fetch(`/api/history?date=${date}`, {
    cache: 'no-store',
    headers: headers(),
  });
  if (!response.ok) throw failure(response, 'The version history');
  return response.json() as Promise<DayHistory>;
}

/**
 * Writes one FHIR Connect mapping and asks openFHIR to re-read its bootstrap directory.
 *
 * A mapping openFHIR rejects is still written — the answer says what went wrong, and seeing that
 * is the reason the editor exists.
 */
export async function saveMapping(file: string, content: string): Promise<SaveResult> {
  const response = await fetch(`/api/mappings/${encodeURIComponent(file)}`, {
    method: 'POST',
    headers: headers({ 'Content-Type': 'text/plain' }),
    body: content,
  });
  if (!response.ok) throw failure(response, 'Saving the mapping');
  return response.json() as Promise<SaveResult>;
}

/** Puts one mapping back the way it shipped. */
export async function resetMapping(file: string): Promise<SaveResult> {
  const response = await fetch(`/api/mappings/${encodeURIComponent(file)}/reset`, {
    method: 'POST',
  });
  if (!response.ok) throw failure(response, 'Resetting the mapping');
  return response.json() as Promise<SaveResult>;
}

/** The mappings as they are on disk right now. */
export async function fetchMappings(): Promise<MappingSource[]> {
  const response = await fetch('/api/mappings', { cache: 'no-store', headers: headers() });
  if (!response.ok) throw failure(response, 'The mappings');
  return response.json() as Promise<MappingSource[]>;
}

/** Runs one AQL query against the record. Read-only: AQL has no write operations. */
export async function runAql(query: string): Promise<AqlResult> {
  const response = await fetch('/api/aql', {
    method: 'POST',
    headers: headers({ 'Content-Type': 'text/plain' }),
    body: query,
  });
  if (!response.ok) throw failure(response, 'The AQL playground');
  return response.json() as Promise<AqlResult>;
}

/** Ready-made queries, each chosen to show one thing about AQL. */
export async function fetchAqlExamples(): Promise<AqlExample[]> {
  const response = await fetch('/api/aql/examples', { headers: headers() });
  if (!response.ok) throw failure(response, 'The AQL playground');
  return response.json() as Promise<AqlExample[]>;
}

/** The operational template as a tree, marked with what the stored data actually uses. */
export async function fetchTemplate(): Promise<TemplateView> {
  const response = await fetch('/api/template', { cache: 'no-store', headers: headers() });
  if (!response.ok) throw failure(response, 'The template explorer');
  return response.json() as Promise<TemplateView>;
}

/** Every rule the mappings declare, read from the files rather than hardcoded. */
export async function fetchMappingRules(): Promise<MappingRule[]> {
  const response = await fetch('/api/mappings/rules', { cache: 'no-store', headers: headers() });
  if (!response.ok) throw failure(response, 'The mapping rules');
  return response.json() as Promise<MappingRule[]>;
}
